var goodData = {
    path:[
        {
            title:'手机·数码·通讯',
            url:'#'
        },
        {
            title:'手机',
            url:'#'
        },
        {
            title:'Apple苹果',
            url:'#'
        },
        {
            title:'iPhone6s系'
        }
    ],
    imagessrc:[],
    goodsDetail:{}
}