var goodData = {
    path:[
        {
            title:'手机·数码·通讯',
            url:'#'
        },
        {
            title:'手机',
            url:'#'
        },
        {
            title:'Apple苹果',
            url:'#'
        },
        {
            title:'iPhone6s系'
        }
    ],
    imagessrc:[
        {b:'./images/b1.png',s:'./images/s1.png'},
        {b:'./images/b2.png',s:'./images/s2.png'},
        {b:'./images/b3.png',s:'./images/s3.png'},
        {b:'./images/b1.png',s:'./images/s1.png'},
        {b:'./images/b2.png',s:'./images/s2.png'},
        {b:'./images/b3.png',s:'./images/s3.png'},
        {b:'./images/b1.png',s:'./images/s1.png'},
        {b:'./images/b2.png',s:'./images/s2.png'},
        {b:'./images/b3.png',s:'./images/s3.png'},
    ],
    goodsDetail:{}
}